/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author briananjune
 */
public class BillingInt extends javax.swing.JFrame {

    /**
     * Creates new form LoginInt
     */
    public BillingInt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButtonNo9 = new javax.swing.JButton();
        jButtonNo8 = new javax.swing.JButton();
        jButtonNo7 = new javax.swing.JButton();
        jButtonNo6 = new javax.swing.JButton();
        jButtonNo5 = new javax.swing.JButton();
        jButtonNo4 = new javax.swing.JButton();
        jButtonNo3 = new javax.swing.JButton();
        jButtonNo2 = new javax.swing.JButton();
        jButtonNo1 = new javax.swing.JButton();
        jButtonNo0 = new javax.swing.JButton();
        jButtonDecimal = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton17 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextSubTotal = new javax.swing.JTextField();
        jTextTax = new javax.swing.JTextField();
        jTextTotal = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextDisplay = new javax.swing.JTextField();
        jTextChange = new javax.swing.JTextField();
        jTextBarCode = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(182, 182, 181));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(73, 72, 71));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(150, 186, 49));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonNo9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonNo9.setText("9");
        jButtonNo9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNo9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonNo9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 90, 120));

        jButtonNo8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonNo8.setText("8");
        jButtonNo8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNo8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonNo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 90, 120));

        jButtonNo7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonNo7.setText("7");
        jButtonNo7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNo7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonNo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 120));

        jButtonNo6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonNo6.setText("6");
        jButtonNo6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNo6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonNo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 90, 120));

        jButtonNo5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonNo5.setText("5");
        jButtonNo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNo5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonNo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 90, 120));

        jButtonNo4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonNo4.setText("4");
        jButtonNo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNo4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonNo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 90, 120));

        jButtonNo3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonNo3.setText("3");
        jButtonNo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNo3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonNo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 90, 120));

        jButtonNo2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonNo2.setText("2");
        jButtonNo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNo2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonNo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 90, 120));

        jButtonNo1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonNo1.setText("1");
        jButtonNo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNo1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonNo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 90, 120));

        jButtonNo0.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonNo0.setText("0");
        jButtonNo0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNo0ActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonNo0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 90, 120));

        jButtonDecimal.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonDecimal.setText(".");
        jButtonDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDecimalActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonDecimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 90, 120));

        jButtonClear.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonClear.setText("C");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 90, 120));

        jPanel7.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 530));

        jPanel1.setBackground(new java.awt.Color(150, 186, 49));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton17.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 120, 110));

        jButton28.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 120, 110));

        jButton29.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 120, 110));

        jButton30.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 120, 110));

        jButton31.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 120, 110));

        jButton32.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 120, 110));

        jButton33.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 120, 110));

        jButton34.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 120, 110));

        jButton35.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 120, 110));

        jButton36.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 120, 110));

        jButton37.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton37ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 120, 110));

        jButton38.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton38ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton38, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 120, 110));

        jButton39.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton39ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton39, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 120, 110));

        jButton40.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton40ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton40, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 120, 110));

        jButton41.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton41ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton41, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, 120, 110));

        jButton42.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton42ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton42, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 120, 110));

        jButton43.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton43ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton43, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 120, 110));

        jButton44.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton44ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton44, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 120, 110));

        jButton45.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton45ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton45, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 390, 120, 110));

        jButton46.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton46ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton46, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 120, 110));

        jPanel7.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 720, 530));

        jTable1.setBackground(new java.awt.Color(150, 186, 49));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Item", "Qty", "Amount"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel7.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 370, 450));

        jPanel4.setBackground(new java.awt.Color(150, 186, 49));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(182, 182, 181));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setText("Print");
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 160, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton4.setText("Remove");
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 160, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton5.setText("Exit");
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 350, -1));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton6.setText("Reset");
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 160, -1));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton7.setText("Pay");
        jPanel3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 160, -1));

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 20, 390, 170));

        jPanel5.setBackground(new java.awt.Color(182, 182, 181));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Total");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("SubTotal");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Tax");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jTextSubTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel5.add(jTextSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 220, -1));

        jTextTax.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel5.add(jTextTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 220, -1));

        jTextTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel5.add(jTextTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 220, -1));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 460, 170));

        jPanel6.setBackground(new java.awt.Color(182, 182, 181));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Payment Method");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Change");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Cash");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Visa Card", "Master Card" }));
        jPanel6.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 160, -1));

        jTextDisplay.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel6.add(jTextDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 220, -1));

        jTextChange.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel6.add(jTextChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 220, -1));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 460, 170));

        jPanel7.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 1400, 210));
        jPanel7.add(jTextBarCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, 370, 80));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNo9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNo9ActionPerformed
        // TODO add your handling code here:
        String Enternumber = jTextDisplay.getText();
        if (Enternumber == "")
        {
            jTextDisplay.setText(jButtonNo9.getText());
        }
        else
        {
            Enternumber = jTextDisplay.getText() + jButtonNo9.getText();
            jTextDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jButtonNo9ActionPerformed

    private void jButtonNo7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNo7ActionPerformed
        // TODO add your handling code here:
        String Enternumber = jTextDisplay.getText();
        if (Enternumber == "")
        {
            jTextDisplay.setText(jButtonNo7.getText());
        }
        else
        {
            Enternumber = jTextDisplay.getText() + jButtonNo7.getText();
            jTextDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jButtonNo7ActionPerformed

    private void jButtonNo8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNo8ActionPerformed
        // TODO add your handling code here:
        String Enternumber = jTextDisplay.getText();
        if (Enternumber == "")
        {
            jTextDisplay.setText(jButtonNo8.getText());
        }
        else
        {
            Enternumber = jTextDisplay.getText() + jButtonNo8.getText();
            jTextDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jButtonNo8ActionPerformed

    private void jButtonNo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNo4ActionPerformed
        // TODO add your handling code here:
        String Enternumber = jTextDisplay.getText();
        if (Enternumber == "")
        {
            jTextDisplay.setText(jButtonNo4.getText());
        }
        else
        {
            Enternumber = jTextDisplay.getText() + jButtonNo4.getText();
            jTextDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jButtonNo4ActionPerformed

    private void jButtonNo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNo5ActionPerformed
        // TODO add your handling code here:
        String Enternumber = jTextDisplay.getText();
        if (Enternumber == "")
        {
            jTextDisplay.setText(jButtonNo5.getText());
        }
        else
        {
            Enternumber = jTextDisplay.getText() + jButtonNo5.getText();
            jTextDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jButtonNo5ActionPerformed

    private void jButtonNo6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNo6ActionPerformed
        // TODO add your handling code here:
        String Enternumber = jTextDisplay.getText();
        if (Enternumber == "")
        {
            jTextDisplay.setText(jButtonNo6.getText());
        }
        else
        {
            Enternumber = jTextDisplay.getText() + jButtonNo6.getText();
            jTextDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jButtonNo6ActionPerformed

    private void jButtonNo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNo1ActionPerformed
        // TODO add your handling code here:
        String Enternumber = jTextDisplay.getText();
        if (Enternumber == "")
        {
            jTextDisplay.setText(jButtonNo1.getText());
        }
        else
        {
            Enternumber = jTextDisplay.getText() + jButtonNo1.getText();
            jTextDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jButtonNo1ActionPerformed

    private void jButtonNo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNo2ActionPerformed
        // TODO add your handling code here:
        String Enternumber = jTextDisplay.getText();
        if (Enternumber == "")
        {
            jTextDisplay.setText(jButtonNo2.getText());
        }
        else
        {
            Enternumber = jTextDisplay.getText() + jButtonNo2.getText();
            jTextDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jButtonNo2ActionPerformed

    private void jButtonNo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNo3ActionPerformed
        // TODO add your handling code here:
        String Enternumber = jTextDisplay.getText();
        if (Enternumber == "")
        {
            jTextDisplay.setText(jButtonNo3.getText());
        }
        else
        {
            Enternumber = jTextDisplay.getText() + jButtonNo3.getText();
            jTextDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jButtonNo3ActionPerformed

    private void jButtonNo0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNo0ActionPerformed
        // TODO add your handling code here:
        String Enternumber = jTextDisplay.getText();
        if (Enternumber == "")
        {
            jTextDisplay.setText(jButtonNo0.getText());
        }
        else
        {
            Enternumber = jTextDisplay.getText() + jButtonNo0.getText();
            jTextDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jButtonNo0ActionPerformed

    private void jButtonDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDecimalActionPerformed
        // TODO add your handling code here:
        if(! jTextDisplay.getText().contains("."))
        {
            jTextDisplay.setText( jTextDisplay.getText() + jButtonDecimal.getText());
        }
    }//GEN-LAST:event_jButtonDecimalActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
        jTextDisplay.setText("");
        jTextChange.setText("");
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton34ActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton35ActionPerformed

    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton36ActionPerformed

    private void jButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton37ActionPerformed

    private void jButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton38ActionPerformed

    private void jButton39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton39ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton39ActionPerformed

    private void jButton40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton40ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton40ActionPerformed

    private void jButton41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton41ActionPerformed

    private void jButton42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton42ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton42ActionPerformed

    private void jButton43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton43ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton43ActionPerformed

    private void jButton44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton44ActionPerformed

    private void jButton45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton45ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton45ActionPerformed

    private void jButton46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton46ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton46ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillingInt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillingInt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillingInt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillingInt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillingInt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonDecimal;
    private javax.swing.JButton jButtonNo0;
    private javax.swing.JButton jButtonNo1;
    private javax.swing.JButton jButtonNo2;
    private javax.swing.JButton jButtonNo3;
    private javax.swing.JButton jButtonNo4;
    private javax.swing.JButton jButtonNo5;
    private javax.swing.JButton jButtonNo6;
    private javax.swing.JButton jButtonNo7;
    private javax.swing.JButton jButtonNo8;
    private javax.swing.JButton jButtonNo9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextBarCode;
    private javax.swing.JTextField jTextChange;
    private javax.swing.JTextField jTextDisplay;
    private javax.swing.JTextField jTextSubTotal;
    private javax.swing.JTextField jTextTax;
    private javax.swing.JTextField jTextTotal;
    // End of variables declaration//GEN-END:variables
}
